### ISSUE TITLE
Very secure ( ͡° ͜ʖ ͡°)

### ISSUE THREAD

**Issue by divadsn** [Albert221/sechat#1]
Any documentation about encryption being used for the secrecy? ( ͡° ͜ʖ ͡°)

**Comment by Albert221** [comment]
There is no documentation whatsoever right now, because backend is still WIP (it's hard to find some time when working full-time & commuting). But I can tell you how it works (will work) under the hood.

It's also worth noting, that I have plans on moving to Signal Protocol in further time if this project will be successfull.

So here's the flow:

1. Albert creates new room.
    - *Symetric key* and *public&private key pair* are generated in Albert's browser.
    - Albert's public key is encoded with *symetric key* and sent to server.
2. Albert gets a page showing an empty chat with an invite link which he sends to David. That link contains chat ID and and *symetric key* appended in the *fragment* part of the URL.
3. David opens the link.
    - David's *public&private key pair* is generated in his browser.
    - David's public key is encoded with *symetric key* and sent to server.
4. Now, both clients have each other's public keys, they decode them using *symetric key* and just start chatting.

🤝
